In [21]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
%matplotlib inline 
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv("ChurnData.csv",encoding = "ISO-8859-1",low_memory=False,delimiter=",")
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [16]:
#seperate inputs
Xdata = np.asarray(df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','internet']])
Xdata[0:10]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.,   1.,   1.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.,   0.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.,   0.,   0.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.,   1.,   1.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.,   1.,   0.,   0.],
       [ 68.,  52.,  17., 120.,   1.,  24.,   0.,   1.,   0.,   0.],
       [ 42.,  40.,   7.,  37.,   2.,   8.,   1.,   1.,   1.,   1.],
       [  9.,  21.,   1.,  17.,   2.,   2.,   0.,   0.,   0.,   0.],
       [ 35.,  50.,  26., 140.,   2.,  21.,   0.,   1.,   0.,   0.],
       [ 49.,  51.,  27.,  63.,   4.,  19.,   0.,   1.,   0.,   1.]])

In [17]:
#seperate outputs and cast the to int 
ydata = np.asarray(df[['churn']].astype(int))
ydata[0:10]

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [18]:
#Normalize Data --> better for machine ...
scaler = preprocessing.StandardScaler().fit(Xdata)
xdata = scaler.transform(Xdata.astype(float))
xdata[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695,  0.64686916,  1.56469673, -0.88640526],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695, -1.54590766, -0.63910148, -0.88640526],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695, -1.54590766, -0.63910148, -0.88640526],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ,  0.64686916,  1.56469673,  1.12815215],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695,  0.64686916, -0.63910148, -0.88640526]])

In [20]:
X_train, X_test, y_train, y_test = train_test_split( xdata, ydata, test_size=0.2, random_state=4)

In [30]:
LogesticReg = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train) 
# c --> over fit solver , closer to 0 --> less over fit 

C:\Users\ABTIN\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [25]:
yhat = LogesticReg.predict(X_test)
print("Predicts: \n",yhat[0:20])
print("Real Results: \n",y_test[0:20])

Predicts: 
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0]
Real Results: 
 [[0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]


In [26]:
yhat_prob = LogesticReg.predict_proba(X_test)
yhat_prob

array([[0.57075413, 0.42924587],
       [0.579248  , 0.420752  ],
       [0.54247944, 0.45752056],
       [0.67890054, 0.32109946],
       [0.54777726, 0.45222274],
       [0.60562274, 0.39437726],
       [0.51708941, 0.48291059],
       [0.5774033 , 0.4225967 ],
       [0.38556203, 0.61443797],
       [0.57108353, 0.42891647],
       [0.53357724, 0.46642276],
       [0.57118922, 0.42881078],
       [0.53807021, 0.46192979],
       [0.39907001, 0.60092999],
       [0.69663639, 0.30336361],
       [0.53215027, 0.46784973],
       [0.48118305, 0.51881695],
       [0.4472895 , 0.5527105 ],
       [0.45474792, 0.54525208],
       [0.58768054, 0.41231946],
       [0.52216227, 0.47783773],
       [0.48103616, 0.51896384],
       [0.67958041, 0.32041959],
       [0.48084985, 0.51915015],
       [0.45938168, 0.54061832],
       [0.73904184, 0.26095816],
       [0.47096607, 0.52903393],
       [0.47439689, 0.52560311],
       [0.50803018, 0.49196982],
       [0.74573121, 0.25426879],
       [0.

In [33]:
from sklearn.metrics import jaccard_score
print("Accuracy:",jaccard_score(y_test, yhat,pos_label=0))

Accuracy: 0.5757575757575758


In [35]:
from sklearn.metrics import classification_report
print (classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       0.70      0.76      0.73        25
           1       0.54      0.47      0.50        15

    accuracy                           0.65        40
   macro avg       0.62      0.61      0.62        40
weighted avg       0.64      0.65      0.64        40

