In [2]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
import numpy as np

In [3]:
X , y = load_iris(return_X_y = True)
#Y --> 0 ,1

In [10]:
X[:18]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3]])

In [16]:
clf = LogisticRegression(solver = 'sag' , multi_class = 'multinomial' , penalty = 'l2')

In [17]:
%%capture
clf .fit(X , y);

In [12]:
xtest = np.array([[5.4, 3.9, 1.7, 0.4],[4.8, 3.4, 1.6, 0.2],[4.7, 3.2, 1.3, 0.2],[5.8, 4. , 1.2, 0.2]])

In [18]:
clf.predict(xtest)

array([0, 0, 0, 0])

In [20]:
print(y[5],y[11],y[2],y[14])

0 0 0 0


In [21]:
clf.score(X,y)

0.9866666666666667

In [23]:
clf.predict_proba(xtest)

array([[9.84633708e-01, 1.53661333e-02, 1.58531133e-07],
       [9.65205844e-01, 3.47935640e-02, 5.91971750e-07],
       [9.73841635e-01, 2.61580618e-02, 3.03129708e-07],
       [9.96478374e-01, 3.52162285e-03, 3.05856060e-09]])