In [1]:
import numpy as np

# Numpy Intro

In [2]:
simpleArray = np.array({1,2,3,4,5})
print(f"simpleArray:\n{simpleArray}")

simpleArray:
{1, 2, 3, 4, 5}


In [3]:
array2D = np.array([[1,2],[3,4],[5,6],[7,8]])
print(f"ndim: {array2D.ndim}")
print(f"shape: {array2D.shape}")
print("numpy dytype:")
print(f"before dtype:\n{array2D}")
array2D = np.array([[1,2],[3,4],[5,6],[7,8]] ,dtype=np.float)
print(f"after dtype:\n{array2D}")

ndim: 2
shape: (4, 2)
numpy dytype:
before dtype:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
after dtype:
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


C:\Users\ABTIN\AppData\Local\Temp/ipykernel_8168/2950897644.py:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array2D = np.array([[1,2],[3,4],[5,6],[7,8]] ,dtype=np.float)


np arrange

In [5]:
arangList = np.arange(20,50)
print(arangList)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


np linspace

In [32]:
linspace_np = np.linspace(0,100,num=1000)
print(len(linspace_np))
print(linspace_np[100:120])

1000
[10.01001001 10.11011011 10.21021021 10.31031031 10.41041041 10.51051051
 10.61061061 10.71071071 10.81081081 10.91091091 11.01101101 11.11111111
 11.21121121 11.31131131 11.41141141 11.51151151 11.61161161 11.71171171
 11.81181181 11.91191191]


# Slicing

In [6]:
array = np.arange(100)
array[20:60:5]

array([20, 25, 30, 35, 40, 45, 50, 55])

In [7]:
sliceArray = slice(0,60,3)
array[sliceArray]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57])

# Array Manipulation

In [8]:
Array = np.arange(20,110)
print(f"Array:\n{Array}")
print(f"ndim: {Array.ndim}")
print(f"shape: {Array.shape}")

#reshape
Array = Array.reshape(6,15)
print(f"Reshaped Array:\n{Array}")
print(f"ndim: {Array.ndim}")
print(f"shape: {Array.shape}")

#transpose
Array = Array.reshape(15,6)
print(f"Array:\n{Array}")
print(f"shape: {Array.shape}")

print("Transpse:\n")
Array = np.transpose(Array)
print(f"Reshaped Array:\n{Array}")
print(f"shape: {Array.shape}")

Array:
[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109]
ndim: 1
shape: (90,)
Reshaped Array:
[[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34]
 [ 35  36  37  38  39  40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64]
 [ 65  66  67  68  69  70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94]
 [ 95  96  97  98  99 100 101 102 103 104 105 106 107 108 109]]
ndim: 2
shape: (6, 15)
Array:
[[ 20  21  22  23  24  25]
 [ 26  27  28  29  30  31]
 [ 32  33  34  35  36  37]
 [ 38  39  40  41  42  43]
 [ 44  45  46  47  48  49]
 [ 50  51  52  53  54  55]
 [ 56  57  58  59  

# Numpy Operations

In [9]:
firstMatrix = np.arange(9).reshape(3,3)
secondMatrix = np.arange(3).reshape(3,1)
print(firstMatrix)
print(secondMatrix)
#add
addMatrix = np.add(firstMatrix,secondMatrix)
print(addMatrix)
#multipaction
multipactionMatrix = np.multiply(firstMatrix,secondMatrix)
print(multipactionMatrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]]


# Numpy Itrating

In [10]:
Array = np.arange(0,50,5)
for index in np.nditer(Array,order="C"):
    print(index,end="-")

0-5-10-15-20-25-30-35-40-45-

In [11]:
for index in np.nditer(Array,order="F"):
    print(index,end="-")

0-5-10-15-20-25-30-35-40-45-

# Important Numpy Commands

In [12]:
Sample = np.arange(0,9).reshape(3,3)

In [13]:
print("Sample Maximum: " , np.amax(Sample))

Sample Maximum:  8


In [14]:
print("Sample Minimum: " , np.min(Sample))

Sample Minimum:  0


In [20]:
print("np.where for finding the index of value")
print("index of number 6: ",np.where(np.arange(0,9) == 6)[0])

np.where for finding the index of value
index of number 6:  [6]


In [22]:
print("np shape: " , Sample.shape)

np shape:  (3, 3)


In [23]:
print("np ndim: " , Sample.ndim)

np ndim:  2


In [24]:
print("np mean: ",np.mean(Sample))

np mean:  4.0


In [25]:
sample_array = np.array([2,7,1,44,0,2,4,99,0.5,23])
print("np sort: " , np.sort(sample_array))

np sort:  [ 0.   0.5  1.   2.   2.   4.   7.  23.  44.  99. ]
