In [3]:
import numpy as np

# Numpy Intro

In [5]:
simpleArray = np.array({1,2,3,4,5})
print(f"simpleArray:\n{simpleArray}")

simpleArray:
{1, 2, 3, 4, 5}


In [26]:
array2D = np.array([[1,2],[3,4],[5,6],[7,8]])
print(f"ndim: {array2D.ndim}")
print(f"shape: {array2D.shape}")
print("numpy dytype:")
print(f"before dtype:\n{array2D}")
array2D = np.array([[1,2],[3,4],[5,6],[7,8]] ,dtype=np.float)
print(f"after dtype:\n{array2D}")

ndim: 2
shape: (4, 2)
numpy dytype:
before dtype:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
after dtype:
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


C:\Users\ABTIN\AppData\Local\Temp/ipykernel_2900/2950897644.py:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array2D = np.array([[1,2],[3,4],[5,6],[7,8]] ,dtype=np.float)


In [25]:
arangList = np.arange(20,50)
print(arangList)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


# Slicing

In [58]:
array = np.arange(100)
array[20:60:5]

array([20, 25, 30, 35, 40, 45, 50, 55])

In [59]:
sliceArray = slice(0,60,3)
array[sliceArray]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57])

# Array Manipulation

In [48]:
Array = np.arange(20,110)
print(f"Array:\n{Array}")
print(f"ndim: {Array.ndim}")
print(f"shape: {Array.shape}")

#reshape
Array = Array.reshape(6,15)
print(f"Reshaped Array:\n{Array}")
print(f"ndim: {Array.ndim}")
print(f"shape: {Array.shape}")

#transpose
Array = Array.reshape(15,6)
print(f"Array:\n{Array}")
print(f"shape: {Array.shape}")

print("Transpse:\n")
Array = np.transpose(Array)
print(f"Reshaped Array:\n{Array}")
print(f"shape: {Array.shape}")

Array:
[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109]
ndim: 1
shape: (90,)
Reshaped Array:
[[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34]
 [ 35  36  37  38  39  40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64]
 [ 65  66  67  68  69  70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94]
 [ 95  96  97  98  99 100 101 102 103 104 105 106 107 108 109]]
ndim: 2
shape: (6, 15)
Array:
[[ 20  21  22  23  24  25]
 [ 26  27  28  29  30  31]
 [ 32  33  34  35  36  37]
 [ 38  39  40  41  42  43]
 [ 44  45  46  47  48  49]
 [ 50  51  52  53  54  55]
 [ 56  57  58  59  

# Numpy Operations

In [57]:
firstMatrix = np.arange(9).reshape(3,3)
secondMatrix = np.arange(3).reshape(3,1)
print(firstMatrix)
print(secondMatrix)
#add
addMatrix = np.add(firstMatrix,secondMatrix)
print(addMatrix)
#multipaction
multipactionMatrix = np.multiply(firstMatrix,secondMatrix)
print(multipactionMatrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]]


# Numpy Itrating

In [63]:
Array = np.arange(0,50,5)
for index in np.nditer(Array,order="C"):
    print(index,end="-")

0-5-10-15-20-25-30-35-40-45-

In [64]:
for index in np.nditer(Array,order="F"):
    print(index,end="-")

0-5-10-15-20-25-30-35-40-45-